use_frameworks!

platform :ios, '8.0'

target 'CATCommonKit_Example' do
  pod 'CATCommonKit', :path => '../'

  target 'CATCommonKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
